site_name: Patent Żeglarski | Baza Wiedzy
theme:
  name: material
  logo: assets/anc.svg 
  language: pl 
  favicon: assets/anc.svg
extra_css:
  - style.css
nav:
  - Ogólna:
    - Strona główna: index.md
    - Budowa jachtu: budowa-jachtu.md
    - Teoria żeglowania: teoria-zeglowania.md
    - Teoria manewrowania: teoria-manewrowania.md
    - Locja: locja.md
    - Przepisy: przepisy.md
    - Nawigacja: nawigacja.md
    - Ratownictwo: ratownictwo.md
    - Meteorologia: meteorologia.md
    - Prace bosmańskie: prace-bosmanskie.md
  - Boczna:
    - Prace bosmańskie: prace-bosmanskie.md
